---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - geerlingguy.homebrew
    - name: geerlingguy.mas
      when: mas_installed_app_ids

  tasks:
    - include: tasks/ansible-setup.yml
